# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opentelemetry/proto/collector/trace/v1/trace_service.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'opentelemetry/proto/collector/trace/v1/trace_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jumpstarter_protocol.opentelemetry.proto.trace.v1 import trace_pb2 as opentelemetry_dot_proto_dot_trace_dot_v1_dot_trace__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:opentelemetry/proto/collector/trace/v1/trace_service.proto\x12&opentelemetry.proto.collector.trace.v1\x1a(opentelemetry/proto/trace/v1/trace.proto\"o\n\x19\x45xportTraceServiceRequest\x12R\n\x0eresource_spans\x18\x01 \x03(\x0b\x32+.opentelemetry.proto.trace.v1.ResourceSpansR\rresourceSpans\"\x88\x01\n\x1a\x45xportTraceServiceResponse\x12j\n\x0fpartial_success\x18\x01 \x01(\x0b\x32\x41.opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccessR\x0epartialSuccess\"g\n\x19\x45xportTracePartialSuccess\x12%\n\x0erejected_spans\x18\x01 \x01(\x03R\rrejectedSpans\x12#\n\rerror_message\x18\x02 \x01(\tR\x0c\x65rrorMessage2\xa2\x01\n\x0cTraceService\x12\x91\x01\n\x06\x45xport\x12\x41.opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest\x1a\x42.opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse\"\x00\x42\xaf\x02\n*com.opentelemetry.proto.collector.trace.v1B\x11TraceServiceProtoP\x01Z1go.opentelemetry.io/proto/otlp/collector/trace/v1\xa2\x02\x04OPCT\xaa\x02&Opentelemetry.Proto.Collector.Trace.V1\xca\x02&Opentelemetry\\Proto\\Collector\\Trace\\V1\xe2\x02\x32Opentelemetry\\Proto\\Collector\\Trace\\V1\\GPBMetadata\xea\x02*Opentelemetry::Proto::Collector::Trace::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opentelemetry.proto.collector.trace.v1.trace_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*com.opentelemetry.proto.collector.trace.v1B\021TraceServiceProtoP\001Z1go.opentelemetry.io/proto/otlp/collector/trace/v1\242\002\004OPCT\252\002&Opentelemetry.Proto.Collector.Trace.V1\312\002&Opentelemetry\\Proto\\Collector\\Trace\\V1\342\0022Opentelemetry\\Proto\\Collector\\Trace\\V1\\GPBMetadata\352\002*Opentelemetry::Proto::Collector::Trace::V1'
  _globals['_EXPORTTRACESERVICEREQUEST']._serialized_start=144
  _globals['_EXPORTTRACESERVICEREQUEST']._serialized_end=255
  _globals['_EXPORTTRACESERVICERESPONSE']._serialized_start=258
  _globals['_EXPORTTRACESERVICERESPONSE']._serialized_end=394
  _globals['_EXPORTTRACEPARTIALSUCCESS']._serialized_start=396
  _globals['_EXPORTTRACEPARTIALSUCCESS']._serialized_end=499
  _globals['_TRACESERVICE']._serialized_start=502
  _globals['_TRACESERVICE']._serialized_end=664
# @@protoc_insertion_point(module_scope)
