# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opentelemetry/proto/collector/metrics/v1/metrics_service.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'opentelemetry/proto/collector/metrics/v1/metrics_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jumpstarter_protocol.opentelemetry.proto.metrics.v1 import metrics_pb2 as opentelemetry_dot_proto_dot_metrics_dot_v1_dot_metrics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>opentelemetry/proto/collector/metrics/v1/metrics_service.proto\x12(opentelemetry.proto.collector.metrics.v1\x1a,opentelemetry/proto/metrics/v1/metrics.proto\"y\n\x1b\x45xportMetricsServiceRequest\x12Z\n\x10resource_metrics\x18\x01 \x03(\x0b\x32/.opentelemetry.proto.metrics.v1.ResourceMetricsR\x0fresourceMetrics\"\x8e\x01\n\x1c\x45xportMetricsServiceResponse\x12n\n\x0fpartial_success\x18\x01 \x01(\x0b\x32\x45.opentelemetry.proto.collector.metrics.v1.ExportMetricsPartialSuccessR\x0epartialSuccess\"t\n\x1b\x45xportMetricsPartialSuccess\x12\x30\n\x14rejected_data_points\x18\x01 \x01(\x03R\x12rejectedDataPoints\x12#\n\rerror_message\x18\x02 \x01(\tR\x0c\x65rrorMessage2\xac\x01\n\x0eMetricsService\x12\x99\x01\n\x06\x45xport\x12\x45.opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceRequest\x1a\x46.opentelemetry.proto.collector.metrics.v1.ExportMetricsServiceResponse\"\x00\x42\xbd\x02\n,com.opentelemetry.proto.collector.metrics.v1B\x13MetricsServiceProtoP\x01Z3go.opentelemetry.io/proto/otlp/collector/metrics/v1\xa2\x02\x04OPCM\xaa\x02(Opentelemetry.Proto.Collector.Metrics.V1\xca\x02(Opentelemetry\\Proto\\Collector\\Metrics\\V1\xe2\x02\x34Opentelemetry\\Proto\\Collector\\Metrics\\V1\\GPBMetadata\xea\x02,Opentelemetry::Proto::Collector::Metrics::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opentelemetry.proto.collector.metrics.v1.metrics_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.opentelemetry.proto.collector.metrics.v1B\023MetricsServiceProtoP\001Z3go.opentelemetry.io/proto/otlp/collector/metrics/v1\242\002\004OPCM\252\002(Opentelemetry.Proto.Collector.Metrics.V1\312\002(Opentelemetry\\Proto\\Collector\\Metrics\\V1\342\0024Opentelemetry\\Proto\\Collector\\Metrics\\V1\\GPBMetadata\352\002,Opentelemetry::Proto::Collector::Metrics::V1'
  _globals['_EXPORTMETRICSSERVICEREQUEST']._serialized_start=154
  _globals['_EXPORTMETRICSSERVICEREQUEST']._serialized_end=275
  _globals['_EXPORTMETRICSSERVICERESPONSE']._serialized_start=278
  _globals['_EXPORTMETRICSSERVICERESPONSE']._serialized_end=420
  _globals['_EXPORTMETRICSPARTIALSUCCESS']._serialized_start=422
  _globals['_EXPORTMETRICSPARTIALSUCCESS']._serialized_end=538
  _globals['_METRICSSERVICE']._serialized_start=541
  _globals['_METRICSSERVICE']._serialized_end=713
# @@protoc_insertion_point(module_scope)
