# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opentelemetry/proto/collector/logs/v1/logs_service.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'opentelemetry/proto/collector/logs/v1/logs_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jumpstarter_protocol.opentelemetry.proto.logs.v1 import logs_pb2 as opentelemetry_dot_proto_dot_logs_dot_v1_dot_logs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8opentelemetry/proto/collector/logs/v1/logs_service.proto\x12%opentelemetry.proto.collector.logs.v1\x1a&opentelemetry/proto/logs/v1/logs.proto\"j\n\x18\x45xportLogsServiceRequest\x12N\n\rresource_logs\x18\x01 \x03(\x0b\x32).opentelemetry.proto.logs.v1.ResourceLogsR\x0cresourceLogs\"\x85\x01\n\x19\x45xportLogsServiceResponse\x12h\n\x0fpartial_success\x18\x01 \x01(\x0b\x32?.opentelemetry.proto.collector.logs.v1.ExportLogsPartialSuccessR\x0epartialSuccess\"q\n\x18\x45xportLogsPartialSuccess\x12\x30\n\x14rejected_log_records\x18\x01 \x01(\x03R\x12rejectedLogRecords\x12#\n\rerror_message\x18\x02 \x01(\tR\x0c\x65rrorMessage2\x9d\x01\n\x0bLogsService\x12\x8d\x01\n\x06\x45xport\x12?.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest\x1a@.opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse\"\x00\x42\xa8\x02\n)com.opentelemetry.proto.collector.logs.v1B\x10LogsServiceProtoP\x01Z0go.opentelemetry.io/proto/otlp/collector/logs/v1\xa2\x02\x04OPCL\xaa\x02%Opentelemetry.Proto.Collector.Logs.V1\xca\x02%Opentelemetry\\Proto\\Collector\\Logs\\V1\xe2\x02\x31Opentelemetry\\Proto\\Collector\\Logs\\V1\\GPBMetadata\xea\x02)Opentelemetry::Proto::Collector::Logs::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opentelemetry.proto.collector.logs.v1.logs_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n)com.opentelemetry.proto.collector.logs.v1B\020LogsServiceProtoP\001Z0go.opentelemetry.io/proto/otlp/collector/logs/v1\242\002\004OPCL\252\002%Opentelemetry.Proto.Collector.Logs.V1\312\002%Opentelemetry\\Proto\\Collector\\Logs\\V1\342\0021Opentelemetry\\Proto\\Collector\\Logs\\V1\\GPBMetadata\352\002)Opentelemetry::Proto::Collector::Logs::V1'
  _globals['_EXPORTLOGSSERVICEREQUEST']._serialized_start=139
  _globals['_EXPORTLOGSSERVICEREQUEST']._serialized_end=245
  _globals['_EXPORTLOGSSERVICERESPONSE']._serialized_start=248
  _globals['_EXPORTLOGSSERVICERESPONSE']._serialized_end=381
  _globals['_EXPORTLOGSPARTIALSUCCESS']._serialized_start=383
  _globals['_EXPORTLOGSPARTIALSUCCESS']._serialized_end=496
  _globals['_LOGSSERVICE']._serialized_start=499
  _globals['_LOGSSERVICE']._serialized_end=656
# @@protoc_insertion_point(module_scope)
