# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opentelemetry/proto/collector/profiles/v1development/profiles_service.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'opentelemetry/proto/collector/profiles/v1development/profiles_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from jumpstarter_protocol.opentelemetry.proto.profiles.v1development import profiles_pb2 as opentelemetry_dot_proto_dot_profiles_dot_v1development_dot_profiles__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKopentelemetry/proto/collector/profiles/v1development/profiles_service.proto\x12\x34opentelemetry.proto.collector.profiles.v1development\x1a\x39opentelemetry/proto/profiles/v1development/profiles.proto\"\xe9\x01\n\x1c\x45xportProfilesServiceRequest\x12i\n\x11resource_profiles\x18\x01 \x03(\x0b\x32<.opentelemetry.proto.profiles.v1development.ResourceProfilesR\x10resourceProfiles\x12^\n\ndictionary\x18\x02 \x01(\x0b\x32>.opentelemetry.proto.profiles.v1development.ProfilesDictionaryR\ndictionary\"\x9c\x01\n\x1d\x45xportProfilesServiceResponse\x12{\n\x0fpartial_success\x18\x01 \x01(\x0b\x32R.opentelemetry.proto.collector.profiles.v1development.ExportProfilesPartialSuccessR\x0epartialSuccess\"p\n\x1c\x45xportProfilesPartialSuccess\x12+\n\x11rejected_profiles\x18\x01 \x01(\x03R\x10rejectedProfiles\x12#\n\rerror_message\x18\x02 \x01(\tR\x0c\x65rrorMessage2\xc7\x01\n\x0fProfilesService\x12\xb3\x01\n\x06\x45xport\x12R.opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest\x1aS.opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceResponse\"\x00\x42\x87\x03\n8com.opentelemetry.proto.collector.profiles.v1developmentB\x14ProfilesServiceProtoP\x01Z?go.opentelemetry.io/proto/otlp/collector/profiles/v1development\xa2\x02\x05OPCPV\xaa\x02\x34Opentelemetry.Proto.Collector.Profiles.V1development\xca\x02\x34Opentelemetry\\Proto\\Collector\\Profiles\\V1development\xe2\x02@Opentelemetry\\Proto\\Collector\\Profiles\\V1development\\GPBMetadata\xea\x02\x38Opentelemetry::Proto::Collector::Profiles::V1developmentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opentelemetry.proto.collector.profiles.v1development.profiles_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n8com.opentelemetry.proto.collector.profiles.v1developmentB\024ProfilesServiceProtoP\001Z?go.opentelemetry.io/proto/otlp/collector/profiles/v1development\242\002\005OPCPV\252\0024Opentelemetry.Proto.Collector.Profiles.V1development\312\0024Opentelemetry\\Proto\\Collector\\Profiles\\V1development\342\002@Opentelemetry\\Proto\\Collector\\Profiles\\V1development\\GPBMetadata\352\0028Opentelemetry::Proto::Collector::Profiles::V1development'
  _globals['_EXPORTPROFILESSERVICEREQUEST']._serialized_start=193
  _globals['_EXPORTPROFILESSERVICEREQUEST']._serialized_end=426
  _globals['_EXPORTPROFILESSERVICERESPONSE']._serialized_start=429
  _globals['_EXPORTPROFILESSERVICERESPONSE']._serialized_end=585
  _globals['_EXPORTPROFILESPARTIALSUCCESS']._serialized_start=587
  _globals['_EXPORTPROFILESPARTIALSUCCESS']._serialized_end=699
  _globals['_PROFILESSERVICE']._serialized_start=702
  _globals['_PROFILESSERVICE']._serialized_end=901
# @@protoc_insertion_point(module_scope)
